language: python
python:
  - "3.8"
before_install: cd poke_restapi
install: 
  - pip install -r requirements.txt
  - python setup.py install
script: python -m pytest --cov-report term --cov=src tests/
after_success:
  - coveralls
