apiVersion: v1
kind: Service
metadata:
  name: shakespearean-service
spec:
  selector:
    app: shakespearean-server
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shakespearean-server
spec:
  selector:
    matchLabels:
      app: shakespearean-server
  replicas: 2
  template:
    metadata:
      labels:
        app: shakespearean-server
    spec:
      containers:
      - name: shakespearean-server
        image: shakespearean-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000